### ISSUE TITLE
RR7.1(cm14.1)编译之后一直自动进入recovery

### ISSUE THREAD

**Issue by CirnoSalt** [wuxianlin/android_device_gree_g0215d#1]
本人尝试用了您的cm14.1分支编译了一个ResurrectionRemix7.1，
编译过程一切顺利，但刷入后机器在首屏GREElogo之后直接再次重启自动进入了recovery，
反复尝试重启均是自动进入recovery……

个人经过排查后发现问题似乎出在预编译的kernel上，
解包boot.img替换为某个成品cm14包中的kernel后即可正常引导，但由于内核签名问题导致wifi、NFC等硬件都无法驱动。

所以想冒昧询问下吴大是否还能修复这个问题……毕竟这个机器有些年头了…………

或者您能提供这台机器适用于Android7.1的kernel来源也是好的，据本人所知官方ROM万年都是6.0，
内核也没有开源，所以这个7.1kernel蛮好奇是哪里来的……（2333

**Comment by wuxianlin** [comment]
你没打patch吧https://github.com/wuxianlin/android_device_gree_g0215d/tree/cm-14.1/patches

**Comment by CirnoSalt** [comment]
噗，折腾一个星期都一直没注意到patch文件夹里的内容，
真是这个原因……解决了，吴大nb！

**Comment by NCLnclNCL** [comment]
> 噗，折腾一个星期都一直没注意到patch文件夹里的内容， 真是这个原因……解决了，吴大nb！

Rom
